version: '3'

services:
  nginx: # 컨테이너의 이름
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3

  web1: # 컨테이너의 이름
    build: . # 현재 경로에 있는 Dockerfile을 참조해서 빌드함
    command: gunicorn fisa_django.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -
    volumes:
      - .:/app # 실행할 프로젝트를 작성할 경로 app
    ports:
      - "8000:8000"
    env_file:
      - .env # env파일까지 작성해줘
  
  web2: # 컨테이너의 이름
    build: . # 현재 경로에 있는 Dockerfile을 참조해서 빌드함
    command: gunicorn fisa_django.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -
    volumes:
      - .:/app # 실행할 프로젝트를 작성할 경로 app
    ports:
      - "8001:8000"
    env_file:
      - .env # env파일까지 작성해줘
  
  web3: # 컨테이너의 이름
    build: . # 현재 경로에 있는 Dockerfile을 참조해서 빌드함
    command: gunicorn fisa_django.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -
    volumes:
      - .:/app # 실행할 프로젝트를 작성할 경로 app
    ports:
      - "8002:8000"
    env_file:
      - .env # env파일까지 작성해줘